{
 "title": "WSO2 Integration Node Metrics",
 "description": "This Dashboard provides an overview of a single WSO2 integration nodes",
 "time": { "from": "2020-08-25T10:59:45.895Z", "to": "2020-08-25T11:14:45.895Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "MI Node",
    "query": "label_values(wso2_integration_server_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "[[node]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(time()-wso2_integration_server_up{instance=\"[[node]]\"})"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "stat",
   "description": "Displays the number of services deployed in this node.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(wso2_integration_service_up{instance=\"[[node]]\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Displays current CPU utilisation of the system. If you observe high CPU utilisation refer below link and get a thread dump and thread usage for further investigations.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"[[node]]\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "graph",
   "description": "Displays max and current used memory. If you observe any abnormalities refer below link and take a heap-dump of the system for further analysis.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{instance=\"[[node]]\",area=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{instance=\"[[node]]\", area=\"heap\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Service List",
   "type": "table-old",
   "description": "Displays services that are deployed in this instance",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service_name,service_type, start_time) (wso2_integration_service_up{instance=\"[[node]]\"}*1000>0)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "description": "Displays the total request count served by this node from the start. Request which resulted in error will be counted here too.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time({__name__ =~\"wso2_integration_.*_request_count_total\",instance=\"[[node]]\"}[$__range]))-  (min_over_time({__name__ =~\"wso2_integration_.*_request_count_total\",instance=\"[[node]]\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "description": "Displays the total error count occurred at this node from the start.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time({__name__ =~\"wso2_integration_.*_request_count_error_total\",instance=\"[[node]]\"}[$__range]))- (min_over_time({__name__ =~\"wso2_integration_.*_request_count_error_total\",instance=\"[[node]]\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "description": "Displays the thread count per state. \nIf you observe higher number of blocked threads refer below link and take a thread dump to analyze further.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"[[node]]\", state=\"RUNNABLE\"}",
     "legendFormat": "Runnable"
    },
    {
     "expr": "jvm_threads_state{instance=\"[[node]]\", state=\"WAITING\"} ",
     "legendFormat": "Waiting"
    },
    {
     "expr": "jvm_threads_state{instance=\"[[node]]\", state=\"BLOCKED\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "jvm_threads_state{instance=\"[[node]]\", state=\"TIMED_WAITING\"}",
     "legendFormat": "Timed Waiting"
    }
   ]
  },
  {
   "title": "Open File Descriptor Count",
   "type": "graph",
   "description": "Displays 'Open' and 'Max' file descriptor count. If open descriptor count is high and exceeding max descriptor count refer below link to increase the max file descriptor count.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"[[node]]\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "process_max_fds{instance=\"[[node]]\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Displays the request rate received by this node during the selected time period. This will also include error requests. ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__ =~\"wso2_integration_.*_request_count_total\",instance=\"[[node]]\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "Displays the error rate occurred at this node during the selected time period. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "reqps", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__ =~\"wso2_integration_.*_request_count_error_total\",instance=\"[[node]]\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "description": "Displays the response time of all requests served by this node in a heat map. Each tile will represent number of requests which fell in to the pre-defined time bucket during the bucket time span.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate({__name__ =~\"wso2_integration_.*_latency_seconds\", instance=\"[[node]]\", le=~\".+\"}[10m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate({__name__ =~\"wso2_integration_.*_latency_seconds\", instance=\"[[node]]\", le=~\".+\"}[10m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "Displays the logs(carbon.log) of this node during the selected time period. If no log entries were logged during the selected time pane will be empty.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{instance=\"[[node]]\"}"
    }
   ]
  }
 ]
}